### PR TITLE
help add Html support

### PR DESCRIPTION
**Pull request by nitrag**
I'm super close to getting this working, I don't think the promises are working correctly though. Can I get some tips/pointers? I can see in the logs that the dataToSend is generated correctly. Line 55.

### CODE REVIEW

**Comment by nitrag** [comment]
@bcomeau can you help me get this working?

**Comment by nitrag** [comment]
I got it working, wasn't getting the proper `to:` parameter

**Comment by bcomeau** [comment]
Great work! I'll be glad to merge this pull request.

I think it might be preferable to have the HTML content in an other file. I could be heavy in `index.js` if it has CSS or Base64 images.

Can you add an example to the **README** where the body is from an external file.

**Comment by nitrag** [comment]
Sure, I'll try to work on that it would simplify having to escape the
quotes.

**Comment by nitrag** [comment]
Well that was easier than I thought it might be! @bcomeau

**Comment by bcomeau** [comment]
Thank you @nitrag for your contribution!

**Pull request merged**
